added video and updated contributing section in documentation
tailwarden/docs.komiser.io pull request #34
Opened 2023-01-23 16:19 UTC by jakepage91

2023-01-23 16:51 UTC, mlabouardy requested changes
A typo to be fixed

2023-01-23 16:51 UTC, mlabouardy commented on docs/Contributing/contribute.md
> +If you're in need of any assiatance at any stage of your contributing journey please don't hesitate to reach out to anybody in the `#general` or `#feedback` discord channels, also let us know if you
assistance

2023-01-23 16:51 UTC, mlabouardy commented on docs/Contributing/contribute.md
> +- Once your pull request has been opened it will be assigned to one or more reviewers. Those reviewers will do a thorough code review, looking for correctness, bugs, opportunities for improvement, do
"has been opened, it will", maybe ?

2023-01-23 16:57 UTC, jakepage91 commented on docs/Contributing/contribute.md
> +If you're in need of any assiatance at any stage of your contributing journey please don't hesitate to reach out to anybody in the `#general` or `#feedback` discord channels, also let us know if you
Should be good now

2023-01-23 17:53 UTC, jakepage91 commented on docs/Contributing/contribute.md
> +- Once your pull request has been opened it will be assigned to one or more reviewers. Those reviewers will do a thorough code review, looking for correctness, bugs, opportunities for improvement, do
Done!

2023-01-24 09:41 UTC, mlabouardy approved these changes
Looks good, thanks

2023-01-24 09:41 UTC, merged